config/routes.rb
IdeaBook::Application.routes.draw do
  devise_for :users

  resources :agencies

  resources :brands do
    resources :projects do
      resources :ideas
    end
  end

  namespace :admin do
    resources :agencies
  end

  root :to => "brands#index"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :project_id, :added_info, :pitch, :title
  belongs_to :project
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= simple_form_for(@idea, :html => {:class => 'form-horizontal' }) do |f| %>
  <%= f.association :project %>
  <%= f.input :title %>
  <%= f.input :pitch, as: :text %>
  <%= f.input :added_info %>
  <%= f.button :submit, :class => "btn btn-success" %>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<div class="idea-listing">

<div class="page-header">
  <h1>Your Ideas <small><%= current_user.email %></small></h1>
</div>

<div class="row">

<% @ideas.each do |idea| %>

<div class="span4">
<div class="media idea">

    <a class="pull-left" href="#">
      <img class="media-object" src="" alt="">
    </a>

    <div class="media-body">
      <h4 class="media-heading title"><%= link_to idea.title, idea %></h4>
      <p class="desc"><%= idea.pitch %></p>
    </div>

</div>
</div>

<% end %>

<div class="span4">

  <div class="new">
    <%= link_to 'Create New Idea', new_idea_path %>
  </div>

</div>

</div>
</div>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<div class="page-header">
  <h1><%= @idea.title %><small> by Joe Turner</small></h1>
</div>

<p id="notice"><%= notice %></p>

<p>
  <%= @idea.pitch %>
</p>

<p>
  <b>Added info:</b>
  <%= @idea.added_info %>
</p>


<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>