config/routes.rb
IdeaBook::Application.routes.draw do
  devise_for :users

  resources :agencies

  resources :brands do
    resources :projects do
      resources :ideas
    end
  end

  namespace :admin do
    resources :agencies
  end

  root :to => "brands#index"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  attr_accessible :city, :country, :email, :name, :agency_id
  has_many :brands
  has_many :users
  has_many :super_users, class_name: 'User', conditions: { super_user: true }
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @agencies }
    end
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
    @agency = Agency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @agency }
    end
  end

  # GET /agencies/new
  # GET /agencies/new.json
  def new
    @agency = Agency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @agency }
    end
  end

  # GET /agencies/1/edit
  def edit
    @agency = Agency.find(params[:id])
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(params[:agency])

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render json: @agency, status: :created, location: @agency }
      else
        format.html { render action: "new" }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /agencies/1
  # PUT /agencies/1.json
  def update
    @agency = Agency.find(params[:id])

    respond_to do |format|
      if @agency.update_attributes(params[:agency])
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency = Agency.find(params[:id])
    @agency.destroy

    respond_to do |format|
      format.html { redirect_to agencies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.erb
<%= simple_form_for(@agency) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :city %>
    <%= f.input :country %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/agencies/edit.html.erb
<h1>Editing agency</h1>

<%= render 'form' %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

app/views/agencies/index.html.erb
<div class="idea-listing">

<div class="page-header">
  <h1>Agencies <small>Currently <%= @agencies.count %></small></h1>
</div>

<div class="row">

<% @agencies.each do |agency| %>

<div class="span4">
<div class="media idea">

    <a class="pull-left" href="#">
      <img class="media-object" src="" alt="">
    </a>

    <div class="media-body">
      <h4 class="media-heading title"><%= link_to agency.name, agency %></h4>
      <p class="desc"><%= agency.city %></p>
      <p class="desc"><%= agency.email %></p>
    </div>

</div>
</div>

<% end %>

<div class="span4">

  <div class="new">
    <%= link_to 'Create New Agency', new_agency_path %>
  </div>

</div>

</div>
</div>

app/views/agencies/new.html.erb
<h1>New agency</h1>

<%= render 'form' %>

<%= link_to 'Back', agencies_path %>

app/views/agencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @agency.name %>
</p>

<p>
  <b>City:</b>
  <%= @agency.city %>
</p>

<p>
  <b>Country:</b>
  <%= @agency.country %>
</p>

<p>
  <b>Email:</b>
  <%= @agency.email %>
</p>


<%= link_to 'Edit', edit_agency_path(@agency) %> |
<%= link_to 'Back', agencies_path %>