config/routes.rb
IdeaBook::Application.routes.draw do
  devise_for :users

  resources :agencies

  resources :brands do
    resources :projects do
      resources :ideas
    end
  end

  namespace :admin do
    resources :agencies
  end

  root :to => "brands#index"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :project_id, :brand_id, :name, :project_end, :project_start, :url
  has_many :ideas
  belongs_to :brand
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %>

<% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.association :brand %>
  <%= f.input :url %>
  <%= f.input :project_start %>
  <%= f.input :project_end %>
  <%= f.button :submit, :class => "btn btn-success" %>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="idea-listing">

<div class="page-header">
  <h1>Your Projects <small><%= current_user.email %></small></h1>
</div>

<div class="row">

<% @projects.each do |project| %>

<div class="span4">
<div class="media idea">

    <a class="pull-left" href="#">
      <img class="media-object" src="" alt="">
    </a>

    <div class="media-body">
      <h4 class="media-heading title"><%= link_to project.name, project %></h4>
      <p class="desc"><%= project.description %></p>
      <p class="desc"><strong><%= project.project_start %> to <%= project.project_end %></strong></p>
    </div>

</div>
</div>

<% end %>

<div class="span4">

  <div class="new">
    <%= link_to 'Create New Project', new_project_path %>
  </div>

</div>

</div>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="idea-listing">

<div class="page-header">
  <h1><%= @project.name %><small> Currently <%= @project.ideas.count %> Ideas</small></h1>
</div>

<div class="row">

<% @project.ideas.each do |idea| %>

<div class="span4">
<div class="media idea">

    <a class="pull-left" href="#">
      <img class="media-object" src="" alt="">
    </a>

    <div class="media-body">
      <h4 class="media-heading title"><%= link_to idea.title, idea %></h4>
      <p class="desc"><%= idea.pitch %></p>
    </div>

</div>
</div>

<% end %>

<div class="span4">

  <div class="new">
    <%= link_to 'Create New Idea', new_idea_path %>
  </div>

</div>

</div>
</div>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>