config/routes.rb
IdeaBook::Application.routes.draw do
  devise_for :users

  resources :agencies

  resources :brands do
    resources :projects do
      resources :ideas
    end
  end

  namespace :admin do
    resources :agencies
  end

  root :to => "brands#index"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :description, :brand_id, :name
  has_many :projects
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  before_filter :authenticate_user!

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render json: @brand, status: :created, location: @brand }
      else
        format.html { render action: "new" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= simple_form_for(@brand) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<div class="idea-listing">

<div class="page-header">
  <h1>Brands <small><%= current_user.agency.name %></small></h1>
</div>

<div class="row">

<% @brands.each do |brand| %>

<div class="span4">
<div class="media idea">

    <a class="pull-left" href="#">
      <img class="media-object" src="" alt="">
    </a>

    <div class="media-body">
      <h4 class="media-heading title"><%= link_to brand.name, brand %></h4>
      <p class="desc"><%= brand.description %></p>
    </div>

</div>
</div>

<% end %>

<div class="span4">

  <div class="new">
    <%= link_to 'Create New Brand', new_brand_path %>
  </div>

</div>

</div>
</div>

app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<div class="idea-listing">

<div class="page-header">
  <h1><%= @brand.name %><small> Currently <%= @brand.projects.count %> Projects</small></h1>
</div>

<div class="row">

<% @brand.projects.each do |project| %>

<div class="span4">
<div class="media idea">

    <a class="pull-left" href="#">
      <img class="media-object" src="" alt="">
    </a>

    <div class="media-body">
      <h4 class="media-heading title"><%= link_to project.name, project %></h4>
      <p class="desc"><%= project.description %></p>
    </div>

</div>
</div>

<% end %>

<div class="span4">

  <div class="new">
    <%= link_to 'Create New Project', new_project_path %>
  </div>

</div>

</div>
</div>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>